//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by GraphicalInterface.rc
//
#define IDD_DIALOG_MAIN                 101
#define IDD_DIALOG_ABOUT                102
#define IDD_DIALOG_PeViewMainDlg        103
#define IDD_DIALOG_OptionPeView         104
#define IDD_DIALOG_SectionTableView     105
#define IDD_DIALOG_DataDirectoryView    106
#define IDD_DIALOG_ExportTableView      107
#define IDD_DIALOG_ImportTableView      108
#define IDD_DIALOG_BaseReLocView        109
#define IDD_DIALOG_IatTableView         110
#define IDD_DIALOG_BoundImportTableView 111
#define IDI_ICON_QianYiShen             112
#define IDD_DIALOG_EncryptingShell      113
#define IDD_DIALOG_DLLInjection         114
#define IDD_DIALOG_HookMain             115
#define IDD_DIALOG_IATHOOK              116
#define IDD_DIALOG_DriverMain           117
#define IDD_DIALOG_DriverLoadNormal     118
#define IDC_LIST_PROCESSLIST            1001
#define IDC_LIST_MODULELIST             1002
#define IDC_BUTTON_PeView               1003
#define IDC_BUTTON_SoftwareShell        1004
#define IDC_BUTTON_Dllinjection         1005
#define IDC_BUTTON_About                1006
#define IDC_BUTTON_EXIT                 1007
#define IDC_BUTTON_AboutExit            1008
#define IDC_BUTTON_HOOK                 1008
#define IDC_EDIT_PointerToSymbolTable   1011
#define IDC_EDIT_Machine                1012
#define IDC_EDIT_NumberOfSections       1013
#define IDC_EDIT_TimeDateStamp          1014
#define IDC_EDIT_NumberOfSymbols        1015
#define IDC_EDIT_SizeOfOptionalHeader   1016
#define IDC_EDIT_Characteristics        1017
#define IDC_EDIT_e_magic                1018
#define IDC_EDIT_e_lfanew               1019
#define IDC_BUTTON_PeViewDlgExit        1021
#define IDC_BUTTON_OptionPeVew          1022
#define IDC_EDIT1                       1022
#define IDC_EDIT_Magic                  1022
#define IDC_EDIT_ExportTable_RVA        1022
#define IDC_EDIT_ExportCharacteristics  1022
#define IDC_EDIT_shell                  1022
#define IDC_EDIT_PID_dll                1022
#define IDC_EDIT_IatHook_pid            1022
#define IDC_EDIT_SelectDriver           1022
#define IDC_BUTTON_SectionView          1023
#define IDC_BUTTON_OptionPeViewExit     1023
#define IDC_EDIT_ExportTable_SIZE       1023
#define IDC_EDIT_ExportTimeDateStamp    1023
#define IDC_EDIT_srcApp                 1023
#define IDC_EDIT_DllPath                1023
#define IDC_EDIT_IatHook_dllAddrInTargetProcess 1023
#define IDC_BUTTON_DirectoryView        1024
#define IDC_EDIT_MajorLinkerVersion     1024
#define IDC_EDIT_ExportMajorVersion     1024
#define IDC_EDIT_IatHook_targetModuleName 1024
#define IDC_EDIT_MinorLinkerVersion     1025
#define IDC_LIST_SectionTableView       1025
#define IDC_EDIT_ExportMinorVersion     1025
#define IDC_EDIT_IatHook_targetFuncName 1025
#define IDC_EDIT_SizeOfCode             1026
#define IDC_BUTTON_SectionTableExit     1026
#define IDC_EDIT_ExportName             1026
#define IDC_EDIT_IatHook_targetFuncOrdinal 1026
#define IDC_EDIT_SizeOfInitializedData  1027
#define IDC_BUTTON_ExportTable_Detailed 1027
#define IDC_EDIT_ExportDllName          1027
#define IDC_EDIT_IatHook_nastyFuncName  1027
#define IDC_EDIT_SizeOfUninitializedData 1028
#define IDC_EDIT_ImportTable_RVA        1028
#define IDC_EDIT_ExportBase             1028
#define IDC_EDIT_IatHook_nastyFuncOrdinal 1028
#define IDC_EDIT_AddressOfEntryPoint    1029
#define IDC_EDIT_ImportTable_SIZE       1029
#define IDC_EDIT_ExportNumbreOfFunctions 1029
#define IDC_EDIT_IatHook_pid_Method2    1029
#define IDC_EDIT_BaseOfCode             1030
#define IDC_EDIT_ResourceTable_RVA      1030
#define IDC_EDIT_ExportNumberOfNames    1030
#define IDC_EDIT_IatHook_targetModuleName_Method2 1030
#define IDC_EDIT_BaseOfData             1031
#define IDC_EDIT_ResourceTable_SIZE     1031
#define IDC_EDIT_ExportAddressOfFunctions 1031
#define IDC_EDIT_IatHook_targetFuncName_Method2 1031
#define IDC_EDIT_ImageBase              1032
#define IDC_EDIT_ExceptionTable_RVA     1032
#define IDC_EDIT_ExportAddressOfNames   1032
#define IDC_EDIT_IatHook_targetFuncOrdinal_Method2 1032
#define IDC_EDIT_SectionAlignment       1033
#define IDC_EDIT_ExceptionTable_SIZE    1033
#define IDC_EDIT_ExportAddressOfNameOrdinals 1033
#define IDC_EDIT_IatHook_targetFuncOrdinalMethod2 1033
#define IDC_EDIT_FileAlignment          1034
#define IDC_EDIT_SecurityTable_RVA      1034
#define IDC_EDIT_MajorOperatingSystemVersion 1035
#define IDC_EDIT_SecurityTable_SIZE     1035
#define IDC_EDIT_MinorOperatingSystemVersion 1036
#define IDC_EDIT_BaseRelocTable_RVA     1036
#define IDC_EDIT_MajorImageVersion      1037
#define IDC_EDIT_BaseRelocTable_SIZE    1037
#define IDC_EDIT_MinorImageVersion      1038
#define IDC_EDIT_DebugTable_RVA         1038
#define IDC_EDIT_MajorSubsystemVersion  1039
#define IDC_EDIT_DebugTable_SIZE        1039
#define IDC_EDIT_MinorSubsystemVersion  1040
#define IDC_EDIT_CopyRightTable_RVA     1040
#define IDC_EDIT_Win32VersionValue      1041
#define IDC_EDIT_CopyRightTable_SIZE    1041
#define IDC_EDIT_SizeOfImage            1042
#define IDC_EDIT_GlobalPtrTable_RVA     1042
#define IDC_EDIT_SizeOfHeaders          1043
#define IDC_EDIT_GlobalPtrTable_SIZE    1043
#define IDC_EDIT_CheckSum               1044
#define IDC_EDIT_TLSTable_RVA           1044
#define IDC_EDIT_Subsystem              1045
#define IDC_EDIT_TLSTable_SIZE          1045
#define IDC_EDIT_DllCharacteristics     1046
#define IDC_EDIT_LoadConfigTable_RVA    1046
#define IDC_EDIT_SizeOfStackReserve     1047
#define IDC_EDIT_LoadConfigTable_SIZE   1047
#define IDC_EDIT_SizeOfStackCommit      1048
#define IDC_EDIT_BoundImportTable_RVA   1048
#define IDC_EDIT_SizeOfHeapReserve      1049
#define IDC_EDIT_BoundImportTable_SIZE  1049
#define IDC_EDIT_SizeOfHeapCommit       1050
#define IDC_EDIT_IATTable_RVA           1050
#define IDC_EDIT_LoaderFlags            1051
#define IDC_EDIT_IATTable_SIZE          1051
#define IDC_EDIT_NumberOfRvaAndSizes    1052
#define IDC_EDIT_DelayImportTable_RVA   1052
#define IDC_EDIT_DelayImportTable_SIZE  1053
#define IDC_EDIT_ComTable_RVA           1054
#define IDC_EDIT_ComTable_SIZE          1055
#define IDC_EDIT_RetainTable_RVA        1056
#define IDC_EDIT_RetainTable_SIZE       1057
#define IDC_BUTTON_ImportTable_Detailed 1058
#define IDC_BUTTON_ResourceTable_Detailed 1059
#define IDC_BUTTON_BaseRelocTable_Detailed 1060
#define IDC_BUTTON_IATTable_Detailed    1061
#define IDC_BUTTON_BoundImportTable_Detailed 1062
#define IDC_BUTTON_DataDirectoryViewExit 1063
#define IDC_LIST_ExportAddressOfFunctionsTable 1064
#define IDC_LIST_ExportOtherTwoTables   1065
#define IDC_BUTTON_ExportTableViewExit  1066
#define IDC_LIST_ImportTableBaseInfo    1067
#define IDC_LIST_ImportFuncByOrdinal    1068
#define IDC_LIST_ImportFuncByName       1069
#define IDC_BUTTON_ImportTableViewExit  1070
#define IDC_LIST_BaseRelocInfo          1071
#define IDC_LIST_BaseRelocDetailed      1072
#define IDC_BUTTON_BaseRelocViewExit    1073
#define IDC_LIST_IatTableInfo           1074
#define IDC_LIST_YesBound               1075
#define IDC_LIST_BoundImportDetailed    1075
#define IDC_LIST_NoBound                1076
#define IDC_BUTTON_IatTableViewExit     1077
#define IDC_LIST_BoundImportInfo        1078
#define IDC_BUTTON_BoundImportViewExit  1079
#define IDC_BUTTON_shell                1080
#define IDC_BUTTON_srcApp               1081
#define IDC_BUTTON_EncryptingShellExit  1082
#define IDC_BUTTON_startEncrypt         1083
#define IDC_BUTTON_selectDll            1084
#define IDC_RADIO_LoadLibrary           1085
#define IDC_RADIO_memoryWrite           1086
#define IDC_RADIO_loadProcess           1087
#define IDC_RADIO_typewriting           1088
#define IDC_BUTTON_exitOfDll            1089
#define IDC_BUTTON_startInject          1090
#define IDC_BUTTON_startUninstall       1091
#define IDC_RADIO_WriteMemoryWithoutRemoteThread 1092
#define IDC_BUTTON_IatHook              1093
#define IDC_BUTTON_IatHook2             1094
#define IDC_BUTTON_InLineHook           1094
#define IDC_BUTTON_HookMainExit         1095
#define IDC_BUTTON_IatHook_start        1097
#define IDC_EDIT_oldFuncAddrValue       1098
#define IDC_EDIT_oldFuncAddrValue_Method2 1099
#define IDC_BUTTON_PROCESSLIST_flushed  1099
#define IDC_BUTTON_IatHook_start_method2 1100
#define IDC_BUTTON_DriverMain           1100
#define IDC_BUTTON_DriveLoadNormal      1101
#define IDC_BUTTON_SelectDriver         1102
#define IDC_BUTTON_Register             1103
#define IDC_BUTTON_Run                  1104
#define IDC_BUTTON_Stop                 1105
#define IDC_BUTTON_UnRegister           1106

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        119
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1107
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
